// Y4Y Directory - WHO Regions & Countries (Client-side mirror)
const WHO_REGIONS_CLIENT = {
  AFRO: {
    name: "African Region", code: "AFRO", color: "#E8A838", emoji: "🌍",
    countries: [
      { name: "Algeria", code: "DZ", provinces: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"], cities: ["Algiers", "Oran", "Constantine"] },
      { name: "Angola", code: "AO", provinces: ["Luanda", "Huambo", "Benguela", "Bié", "Malanje"], cities: ["Luanda", "Huambo", "Benguela"] },
      { name: "Benin", code: "BJ", provinces: ["Alibori", "Atacora", "Atlantique", "Borgou", "Collines"], cities: ["Cotonou", "Porto-Novo", "Parakou"] },
      { name: "Botswana", code: "BW", provinces: ["Central", "Ghanzi", "Kgalagadi", "Kgatleng", "Kweneng"], cities: ["Gaborone", "Francistown", "Molepolole"] },
      { name: "Burkina Faso", code: "BF", provinces: ["Boucle du Mouhoun", "Cascades", "Centre", "Centre-Est", "Centre-Nord"], cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"] },
      { name: "Burundi", code: "BI", provinces: ["Bubanza", "Bujumbura Mairie", "Bujumbura Rural", "Bururi", "Cankuzo"], cities: ["Bujumbura", "Muyinga", "Gitega"] },
      { name: "Cabo Verde", code: "CV", provinces: ["Barlavento", "Sotavento"], cities: ["Praia", "Mindelo", "Santa Maria"] },
      { name: "Cameroon", code: "CM", provinces: ["Adamawa", "Centre", "East", "Far North", "Littoral"], cities: ["Yaoundé", "Douala", "Garoua"] },
      { name: "Central African Republic", code: "CF", provinces: ["Bangui", "Basse-Kotto", "Haute-Kotto"], cities: ["Bangui", "Bimbo", "Mbaïki"] },
      { name: "Chad", code: "TD", provinces: ["Batha", "Borkou", "Chari-Baguirmi", "Ennedi-Est"], cities: ["N'Djamena", "Moundou", "Sarh"] },
      { name: "Comoros", code: "KM", provinces: ["Grande Comore", "Anjouan", "Mohéli"], cities: ["Moroni", "Mutsamudu", "Fomboni"] },
      { name: "Congo", code: "CG", provinces: ["Bouenza", "Cuvette", "Kouilou", "Lékoumou"], cities: ["Brazzaville", "Pointe-Noire", "Dolisie"] },
      { name: "Côte d'Ivoire", code: "CI", provinces: ["Abidjan", "Bas-Sassandra", "Comoé"], cities: ["Abidjan", "Bouaké", "Daloa"] },
      { name: "Democratic Republic of the Congo", code: "CD", provinces: ["Bandundu", "Bas-Congo", "Équateur", "Kasaï-Occidental"], cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"] },
      { name: "Djibouti", code: "DJ", provinces: ["Ali Sabieh", "Arta", "Dikhil", "Djibouti"], cities: ["Djibouti City", "Ali Sabieh", "Tadjourah"] },
      { name: "Equatorial Guinea", code: "GQ", provinces: ["Annobón", "Bioko Norte", "Bioko Sur"], cities: ["Malabo", "Bata", "Ebebiyín"] },
      { name: "Eritrea", code: "ER", provinces: ["Anseba", "Debub", "Gash-Barka", "Maekel"], cities: ["Asmara", "Keren", "Massawa"] },
      { name: "Eswatini", code: "SZ", provinces: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"], cities: ["Mbabane", "Manzini", "Lobamba"] },
      { name: "Ethiopia", code: "ET", provinces: ["Addis Ababa", "Afar", "Amhara", "Gambela"], cities: ["Addis Ababa", "Dire Dawa", "Mekelle"] },
      { name: "Gabon", code: "GA", provinces: ["Estuaire", "Haut-Ogooué", "Moyen-Ogooué"], cities: ["Libreville", "Port-Gentil", "Franceville"] },
      { name: "Gambia", code: "GM", provinces: ["Banjul", "Central River", "Lower River", "North Bank"], cities: ["Banjul", "Serekunda", "Brikama"] },
      { name: "Ghana", code: "GH", provinces: ["Ashanti", "Bono", "Central", "Eastern", "Greater Accra"], cities: ["Accra", "Kumasi", "Tamale"] },
      { name: "Guinea", code: "GN", provinces: ["Boké", "Conakry", "Faranah", "Kankan"], cities: ["Conakry", "Nzérékoré", "Kindia"] },
      { name: "Guinea-Bissau", code: "GW", provinces: ["Bafatá", "Biombo", "Bissau", "Bolama"], cities: ["Bissau", "Bafatá", "Gabú"] },
      { name: "Kenya", code: "KE", provinces: ["Nairobi", "Coast", "Central", "Eastern", "Rift Valley"], cities: ["Nairobi", "Mombasa", "Kisumu"] },
      { name: "Lesotho", code: "LS", provinces: ["Berea", "Butha-Buthe", "Leribe", "Maseru"], cities: ["Maseru", "Teyateyaneng", "Mafeteng"] },
      { name: "Liberia", code: "LR", provinces: ["Bomi", "Bong", "Grand Bassa", "Montserrado"], cities: ["Monrovia", "Gbarnga", "Kakata"] },
      { name: "Madagascar", code: "MG", provinces: ["Antananarivo", "Antsiranana", "Fianarantsoa", "Mahajanga", "Toamasina"], cities: ["Antananarivo", "Toamasina", "Antsirabe"] },
      { name: "Malawi", code: "MW", provinces: ["Central", "Northern", "Southern"], cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
      { name: "Mali", code: "ML", provinces: ["Kayes", "Koulikoro", "Sikasso", "Ségou", "Mopti"], cities: ["Bamako", "Sikasso", "Mopti"] },
      { name: "Mauritania", code: "MR", provinces: ["Adrar", "Assaba", "Brakna", "Gorgol"], cities: ["Nouakchott", "Nouadhibou", "Rosso"] },
      { name: "Mauritius", code: "MU", provinces: ["Port Louis", "Black River", "Flacq", "Grand Port"], cities: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix"] },
      { name: "Mozambique", code: "MZ", provinces: ["Cabo Delgado", "Gaza", "Inhambane", "Maputo"], cities: ["Maputo", "Matola", "Nampula"] },
      { name: "Namibia", code: "NA", provinces: ["Erongo", "Hardap", "Kavango East", "Khomas"], cities: ["Windhoek", "Rundu", "Walvis Bay"] },
      { name: "Niger", code: "NE", provinces: ["Agadez", "Diffa", "Dosso", "Maradi", "Tahoua"], cities: ["Niamey", "Zinder", "Maradi"] },
      { name: "Nigeria", code: "NG", provinces: ["Abia", "Adamawa", "Anambra", "Bauchi", "Lagos"], cities: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt"] },
      { name: "Rwanda", code: "RW", provinces: ["Kigali", "Eastern", "Northern", "Southern", "Western"], cities: ["Kigali", "Butare", "Gitarama"] },
      { name: "São Tomé and Príncipe", code: "ST", provinces: ["São Tomé", "Príncipe"], cities: ["São Tomé"] },
      { name: "Senegal", code: "SN", provinces: ["Dakar", "Diourbel", "Fatick", "Kaolack"], cities: ["Dakar", "Touba", "Thiès"] },
      { name: "Seychelles", code: "SC", provinces: ["Anse aux Pins", "Central Mahé", "La Rivière Anglaise"], cities: ["Victoria"] },
      { name: "Sierra Leone", code: "SL", provinces: ["Eastern", "Northern", "Southern", "Western"], cities: ["Freetown", "Bo", "Kenema"] },
      { name: "Somalia", code: "SO", provinces: ["Awdal", "Bakool", "Banaadir", "Bari", "Bay"], cities: ["Mogadishu", "Hargeisa", "Bosaso"] },
      { name: "South Africa", code: "ZA", provinces: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Western Cape"], cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria"] },
      { name: "South Sudan", code: "SS", provinces: ["Central Equatoria", "Eastern Equatoria", "Jonglei", "Lakes"], cities: ["Juba", "Malakal", "Wau"] },
      { name: "Tanzania", code: "TZ", provinces: ["Arusha", "Dar es Salaam", "Dodoma", "Iringa", "Mwanza"], cities: ["Dar es Salaam", "Mwanza", "Arusha"] },
      { name: "Togo", code: "TG", provinces: ["Centrale", "Kara", "Maritime", "Plateaux", "Savanes"], cities: ["Lomé", "Sokodé", "Kara"] },
      { name: "Uganda", code: "UG", provinces: ["Central", "Eastern", "Northern", "Western"], cities: ["Kampala", "Gulu", "Lira"] },
      { name: "Zambia", code: "ZM", provinces: ["Central", "Copperbelt", "Eastern", "Luapula", "Lusaka"], cities: ["Lusaka", "Kitwe", "Ndola"] },
      { name: "Zimbabwe", code: "ZW", provinces: ["Bulawayo", "Harare", "Manicaland", "Mashonaland Central", "Mashonaland East"], cities: ["Harare", "Bulawayo", "Chitungwiza"] }
    ]
  },
  AMRO: {
    name: "Region of the Americas", code: "AMRO", color: "#2E86AB", emoji: "🌎",
    countries: [
      { name: "Antigua and Barbuda", code: "AG", provinces: ["Saint George", "Saint John", "Saint Mary"], cities: ["Saint John's"] },
      { name: "Argentina", code: "AR", provinces: ["Buenos Aires", "Catamarca", "Chaco", "Córdoba", "Mendoza"], cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"] },
      { name: "Bahamas", code: "BS", provinces: ["New Providence", "Grand Bahama", "Andros"], cities: ["Nassau", "Freeport", "Lucaya"] },
      { name: "Barbados", code: "BB", provinces: ["Christ Church", "Saint Andrew", "Saint George", "Saint James"], cities: ["Bridgetown", "Speightstown", "Oistins"] },
      { name: "Belize", code: "BZ", provinces: ["Belize", "Cayo", "Corozal", "Orange Walk", "Stann Creek"], cities: ["Belmopan", "Belize City", "Dangriga"] },
      { name: "Bolivia", code: "BO", provinces: ["Beni", "Chuquisaca", "Cochabamba", "La Paz", "Oruro"], cities: ["Sucre", "La Paz", "Cochabamba", "Santa Cruz"] },
      { name: "Brazil", code: "BR", provinces: ["Acre", "Alagoas", "Amazonas", "Bahia", "São Paulo"], cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"] },
      { name: "Canada", code: "CA", provinces: ["Alberta", "British Columbia", "Manitoba", "Ontario", "Quebec"], cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa"] },
      { name: "Chile", code: "CL", provinces: ["Antofagasta", "Araucanía", "Atacama", "Biobío", "Santiago"], cities: ["Santiago", "Valparaíso", "Concepción"] },
      { name: "Colombia", code: "CO", provinces: ["Antioquia", "Atlántico", "Bogotá", "Bolívar", "Valle del Cauca"], cities: ["Bogotá", "Medellín", "Cali", "Barranquilla"] },
      { name: "Costa Rica", code: "CR", provinces: ["Alajuela", "Cartago", "Guanacaste", "Heredia", "San José"], cities: ["San José", "Alajuela", "Desamparados"] },
      { name: "Cuba", code: "CU", provinces: ["Camagüey", "Ciego de Ávila", "Granma", "Havana", "Santiago de Cuba"], cities: ["Havana", "Santiago de Cuba", "Camagüey"] },
      { name: "Dominica", code: "DM", provinces: ["Saint Andrew", "Saint George", "Saint John", "Saint Joseph"], cities: ["Roseau", "Portsmouth", "Marigot"] },
      { name: "Dominican Republic", code: "DO", provinces: ["Azua", "Barahona", "Dajabón", "Duarte", "Santiago"], cities: ["Santo Domingo", "Santiago de los Caballeros", "La Romana"] },
      { name: "Ecuador", code: "EC", provinces: ["Azuay", "Bolívar", "Chimborazo", "Guayas", "Pichincha"], cities: ["Quito", "Guayaquil", "Cuenca"] },
      { name: "El Salvador", code: "SV", provinces: ["Ahuachapán", "Chalatenango", "Cuscatlán", "La Libertad", "San Salvador"], cities: ["San Salvador", "Soyapango", "Santa Ana"] },
      { name: "Grenada", code: "GD", provinces: ["Saint Andrew", "Saint George", "Saint John"], cities: ["St. George's", "Gouyave", "Grenville"] },
      { name: "Guatemala", code: "GT", provinces: ["Alta Verapaz", "Chimaltenango", "Chiquimula", "Guatemala", "Quetzaltenango"], cities: ["Guatemala City", "Quetzaltenango", "Mixco"] },
      { name: "Guyana", code: "GY", provinces: ["Demerara-Mahaica", "East Berbice-Corentyne", "Essequibo Islands-West Demerara"], cities: ["Georgetown", "Linden", "New Amsterdam"] },
      { name: "Haiti", code: "HT", provinces: ["Artibonite", "Centre", "Grand'Anse", "Nord"], cities: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves"] },
      { name: "Honduras", code: "HN", provinces: ["Atlántida", "Choluteca", "Comayagua", "Copán", "Francisco Morazán"], cities: ["Tegucigalpa", "San Pedro Sula", "La Ceiba"] },
      { name: "Jamaica", code: "JM", provinces: ["Clarendon", "Hanover", "Kingston", "Manchester", "Saint Andrew"], cities: ["Kingston", "Montego Bay", "Portmore"] },
      { name: "Mexico", code: "MX", provinces: ["Chihuahua", "Ciudad de México", "Jalisco", "Nuevo León", "Veracruz"], cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"] },
      { name: "Nicaragua", code: "NI", provinces: ["Boaco", "Carazo", "Chinandega", "Estelí", "Managua"], cities: ["Managua", "León", "Masaya"] },
      { name: "Panama", code: "PA", provinces: ["Bocas del Toro", "Chiriquí", "Coclé", "Colón", "Panamá"], cities: ["Panama City", "Colón", "David"] },
      { name: "Paraguay", code: "PY", provinces: ["Alto Paraná", "Amambay", "Asunción", "Central", "Itapúa"], cities: ["Asunción", "Ciudad del Este", "Encarnación"] },
      { name: "Peru", code: "PE", provinces: ["Arequipa", "Ayacucho", "Cusco", "La Libertad", "Lima"], cities: ["Lima", "Arequipa", "Callao", "Cusco"] },
      { name: "Saint Kitts and Nevis", code: "KN", provinces: ["Saint George Basseterre", "Saint Paul Charlestown"], cities: ["Basseterre", "Charlestown"] },
      { name: "Saint Lucia", code: "LC", provinces: ["Anse la Raye", "Castries", "Choiseul", "Dennery"], cities: ["Castries", "Bisée", "Vieux Fort"] },
      { name: "Saint Vincent and the Grenadines", code: "VC", provinces: ["Charlotte", "Grenadines", "Saint Andrew", "Saint George"], cities: ["Kingstown", "Georgetown", "Barrouallie"] },
      { name: "Suriname", code: "SR", provinces: ["Brokopondo", "Commewijne", "Coronie", "Nickerie", "Paramaribo"], cities: ["Paramaribo", "Lelydorp", "Nieuw Nickerie"] },
      { name: "Trinidad and Tobago", code: "TT", provinces: ["Arima", "Chaguanas", "Diego Martin", "Port of Spain", "San Fernando"], cities: ["Port of Spain", "Chaguanas", "San Fernando"] },
      { name: "United States of America", code: "US", provinces: ["California", "Florida", "New York", "Texas", "Washington"], cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"] },
      { name: "Uruguay", code: "UY", provinces: ["Artigas", "Canelones", "Cerro Largo", "Colonia", "Montevideo"], cities: ["Montevideo", "Salto", "Paysandú"] },
      { name: "Venezuela", code: "VE", provinces: ["Anzoátegui", "Aragua", "Bolívar", "Carabobo", "Caracas"], cities: ["Caracas", "Maracaibo", "Valencia"] }
    ]
  },
  SEARO: {
    name: "South-East Asia Region", code: "SEARO", color: "#A23B72", emoji: "🌏",
    countries: [
      { name: "Bangladesh", code: "BD", provinces: ["Barisal", "Chittagong", "Dhaka", "Khulna", "Mymensingh", "Rajshahi", "Rangpur", "Sylhet"], cities: ["Dhaka", "Chittagong", "Khulna", "Rajshahi"] },
      { name: "Bhutan", code: "BT", provinces: ["Bumthang", "Chukha", "Dagana", "Gasa", "Ha", "Paro", "Thimphu"], cities: ["Thimphu", "Phuntsholing", "Punakha"] },
      { name: "Democratic People's Republic of Korea", code: "KP", provinces: ["Chagang", "North Hamgyong", "South Hamgyong", "Pyongyang"], cities: ["Pyongyang", "Hamhung", "Chongjin"] },
      { name: "India", code: "IN", provinces: ["Andhra Pradesh", "Assam", "Bihar", "Delhi", "Gujarat", "Karnataka", "Kerala", "Maharashtra", "Tamil Nadu", "Uttar Pradesh", "West Bengal"], cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata"] },
      { name: "Indonesia", code: "ID", provinces: ["Aceh", "Bali", "Banten", "East Java", "East Kalimantan", "Jakarta", "West Java", "West Sumatra"], cities: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"] },
      { name: "Maldives", code: "MV", provinces: ["Addu Atoll", "Central Province", "Male", "North Province"], cities: ["Malé", "Addu City", "Fuvahmulah"] },
      { name: "Myanmar", code: "MM", provinces: ["Ayeyarwady", "Bago", "Chin", "Kachin", "Kayah", "Mandalay", "Yangon"], cities: ["Naypyidaw", "Yangon", "Mandalay"] },
      { name: "Nepal", code: "NP", provinces: ["Bagmati", "Gandaki", "Karnali", "Lumbini", "Madhesh", "Sudurpashchim"], cities: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur"] },
      { name: "Sri Lanka", code: "LK", provinces: ["Central", "Eastern", "Northern", "North Western", "Sabaragamuwa", "Southern", "Western"], cities: ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa"] },
      { name: "Thailand", code: "TH", provinces: ["Bangkok", "Chiang Mai", "Chiang Rai", "Chonburi", "Nonthaburi", "Phuket", "Songkhla"], cities: ["Bangkok", "Nonthaburi", "Pak Kret", "Hat Yai"] },
      { name: "Timor-Leste", code: "TL", provinces: ["Aileu", "Ainaro", "Baucau", "Bobonaro", "Dili"], cities: ["Dili", "Baucau", "Maliana"] }
    ]
  },
  EURO: {
    name: "European Region", code: "EURO", color: "#3D5A80", emoji: "🌍",
    countries: [
      { name: "Albania", code: "AL", provinces: ["Berat", "Dibër", "Durrës", "Elbasan", "Fier", "Tirana"], cities: ["Tirana", "Durrës", "Vlorë"] },
      { name: "Andorra", code: "AD", provinces: ["Andorra la Vella", "Canillo", "Encamp", "Escaldes-Engordany", "La Massana"], cities: ["Andorra la Vella"] },
      { name: "Armenia", code: "AM", provinces: ["Aragatsotn", "Ararat", "Armavir", "Gegharkunik", "Kotayk", "Yerevan"], cities: ["Yerevan", "Gyumri", "Vanadzor"] },
      { name: "Austria", code: "AT", provinces: ["Burgenland", "Carinthia", "Lower Austria", "Salzburg", "Styria", "Tyrol", "Vienna"], cities: ["Vienna", "Graz", "Linz", "Salzburg"] },
      { name: "Azerbaijan", code: "AZ", provinces: ["Absheron", "Baku", "Ganja", "Guba-Khachmaz", "Lankaran"], cities: ["Baku", "Ganja", "Sumqayit"] },
      { name: "Belarus", code: "BY", provinces: ["Brest", "Gomel", "Grodno", "Minsk", "Mogilev", "Vitebsk"], cities: ["Minsk", "Homyel", "Vitebsk"] },
      { name: "Belgium", code: "BE", provinces: ["Antwerp", "Brussels", "East Flanders", "Hainaut", "Liège", "West Flanders"], cities: ["Brussels", "Antwerp", "Ghent", "Charleroi"] },
      { name: "Bosnia and Herzegovina", code: "BA", provinces: ["Federation of B&H", "Republika Srpska", "Brčko District"], cities: ["Sarajevo", "Banja Luka", "Tuzla"] },
      { name: "Bulgaria", code: "BG", provinces: ["Burgas", "Plovdiv", "Ruse", "Sofia", "Stara Zagora", "Varna"], cities: ["Sofia", "Plovdiv", "Varna", "Burgas"] },
      { name: "Croatia", code: "HR", provinces: ["Dubrovnik-Neretva", "Istria", "Primorje-Gorski Kotar", "Split-Dalmatia", "Zagreb"], cities: ["Zagreb", "Split", "Rijeka", "Osijek"] },
      { name: "Cyprus", code: "CY", provinces: ["Famagusta", "Kyrenia", "Larnaca", "Limassol", "Nicosia"], cities: ["Nicosia", "Limassol", "Larnaca"] },
      { name: "Czechia", code: "CZ", provinces: ["Central Bohemian", "Moravian-Silesian", "Olomouc", "Prague", "South Bohemian", "South Moravian"], cities: ["Prague", "Brno", "Ostrava", "Plzen"] },
      { name: "Denmark", code: "DK", provinces: ["Capital Region", "Central Denmark", "North Denmark", "Zealand", "Southern Denmark"], cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
      { name: "Estonia", code: "EE", provinces: ["Harju", "Hiiu", "Ida-Viru", "Pärnu", "Tartu"], cities: ["Tallinn", "Tartu", "Narva"] },
      { name: "Finland", code: "FI", provinces: ["Central Finland", "Kainuu", "Lapland", "Pirkanmaa", "Uusimaa"], cities: ["Helsinki", "Espoo", "Tampere", "Vantaa"] },
      { name: "France", code: "FR", provinces: ["Auvergne-Rhône-Alpes", "Brittany", "Grand Est", "Île-de-France", "Occitanie", "Provence-Alpes-Côte d'Azur"], cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"] },
      { name: "Georgia", code: "GE", provinces: ["Adjara", "Guria", "Imereti", "Kvemo Kartli", "Tbilisi"], cities: ["Tbilisi", "Kutaisi", "Batumi"] },
      { name: "Germany", code: "DE", provinces: ["Baden-Württemberg", "Bavaria", "Berlin", "Hamburg", "North Rhine-Westphalia", "Saxony"], cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"] },
      { name: "Greece", code: "GR", provinces: ["Attica", "Central Greece", "Central Macedonia", "Crete", "South Aegean"], cities: ["Athens", "Thessaloniki", "Patras", "Heraklion"] },
      { name: "Hungary", code: "HU", provinces: ["Bács-Kiskun", "Baranya", "Borsod-Abaúj-Zemplén", "Budapest", "Hajdú-Bihar"], cities: ["Budapest", "Debrecen", "Szeged", "Pécs"] },
      { name: "Iceland", code: "IS", provinces: ["Capital Region", "Northeastern Region", "Southern Region", "Western Region"], cities: ["Reykjavik", "Kópavogur", "Hafnarfjörður"] },
      { name: "Ireland", code: "IE", provinces: ["Connacht", "Leinster", "Munster", "Ulster"], cities: ["Dublin", "Cork", "Limerick", "Galway"] },
      { name: "Israel", code: "IL", provinces: ["Central", "Haifa", "Jerusalem", "Northern", "Southern", "Tel Aviv"], cities: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion"] },
      { name: "Italy", code: "IT", provinces: ["Apulia", "Calabria", "Campania", "Emilia-Romagna", "Lazio", "Lombardy", "Sicily", "Veneto"], cities: ["Rome", "Milan", "Naples", "Turin", "Palermo"] },
      { name: "Kazakhstan", code: "KZ", provinces: ["Akmola", "Aktobe", "Almaty", "Atyrau", "East Kazakhstan", "Nur-Sultan"], cities: ["Nur-Sultan", "Almaty", "Shymkent"] },
      { name: "Kyrgyzstan", code: "KG", provinces: ["Batken", "Bishkek", "Chuy", "Issyk-Kul", "Jalal-Abad"], cities: ["Bishkek", "Osh", "Jalal-Abad"] },
      { name: "Latvia", code: "LV", provinces: ["Adaži", "Aizkraukle", "Jēkabpils", "Riga", "Valmiera"], cities: ["Riga", "Daugavpils", "Liepāja"] },
      { name: "Lithuania", code: "LT", provinces: ["Alytus", "Kaunas", "Klaipėda", "Panevėžys", "Vilnius"], cities: ["Vilnius", "Kaunas", "Klaipėda"] },
      { name: "Luxembourg", code: "LU", provinces: ["Esch-sur-Alzette", "Grevenmacher", "Luxembourg"], cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"] },
      { name: "Malta", code: "MT", provinces: ["Gozo", "Malta"], cities: ["Valletta", "Birkirkara", "Mosta"] },
      { name: "Monaco", code: "MC", provinces: ["Monaco"], cities: ["Monaco"] },
      { name: "Montenegro", code: "ME", provinces: ["Bar", "Berane", "Bijelo Polje", "Budva", "Podgorica"], cities: ["Podgorica", "Nikšić", "Herceg Novi"] },
      { name: "Netherlands", code: "NL", provinces: ["Gelderland", "Groningen", "North Holland", "South Holland", "Utrecht"], cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
      { name: "North Macedonia", code: "MK", provinces: ["Berovo", "Bitola", "Kumanovo", "Ohrid", "Skopje"], cities: ["Skopje", "Bitola", "Kumanovo"] },
      { name: "Norway", code: "NO", provinces: ["Agder", "Innlandet", "Møre og Romsdal", "Nordland", "Oslo", "Viken"], cities: ["Oslo", "Bergen", "Stavanger", "Trondheim"] },
      { name: "Poland", code: "PL", provinces: ["Greater Poland", "Lesser Poland", "Lower Silesian", "Łódź", "Masovian", "Silesian"], cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"] },
      { name: "Portugal", code: "PT", provinces: ["Alentejo", "Algarve", "Centro", "Lisbon", "North"], cities: ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora"] },
      { name: "Republic of Moldova", code: "MD", provinces: ["Bălți", "Cahul", "Chișinău", "Comrat", "Soroca"], cities: ["Chișinău", "Tiraspol", "Bălți"] },
      { name: "Romania", code: "RO", provinces: ["Bihor", "Brașov", "Cluj", "Constanța", "Iași", "Prahova"], cities: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"] },
      { name: "Russian Federation", code: "RU", provinces: ["Krasnodar Krai", "Leningrad Oblast", "Moscow", "Moscow Oblast", "Novosibirsk Oblast", "Sverdlovsk Oblast"], cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"] },
      { name: "San Marino", code: "SM", provinces: ["Acquaviva", "Borgo Maggiore", "San Marino"], cities: ["City of San Marino"] },
      { name: "Serbia", code: "RS", provinces: ["Belgrade", "Bor", "Jablanica", "Kolubara", "Mačva"], cities: ["Belgrade", "Novi Sad", "Niš"] },
      { name: "Slovakia", code: "SK", provinces: ["Banská Bystrica", "Bratislava", "Košice", "Nitra", "Prešov", "Žilina"], cities: ["Bratislava", "Košice", "Prešov", "Žilina"] },
      { name: "Slovenia", code: "SI", provinces: ["Central Slovenia", "Coastal-Karst", "Drava", "Lower Sava", "Upper Carniola"], cities: ["Ljubljana", "Maribor", "Celje"] },
      { name: "Spain", code: "ES", provinces: ["Andalusia", "Catalonia", "Community of Madrid", "Valencia", "Basque Country", "Galicia"], cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"] },
      { name: "Sweden", code: "SE", provinces: ["Dalarna", "Gotland", "Norrbotten", "Stockholm", "Västra Götaland"], cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"] },
      { name: "Switzerland", code: "CH", provinces: ["Aargau", "Bern", "Geneva", "Lucerne", "Zürich"], cities: ["Zürich", "Geneva", "Basel", "Lausanne", "Bern"] },
      { name: "Tajikistan", code: "TJ", provinces: ["Gorno-Badakhshan", "Khatlon", "Sughd", "Dushanbe"], cities: ["Dushanbe", "Khujand", "Kulob"] },
      { name: "Turkey", code: "TR", provinces: ["Ankara", "Antalya", "Bursa", "Gaziantep", "Istanbul", "Izmir"], cities: ["Istanbul", "Ankara", "İzmir", "Bursa", "Antalya"] },
      { name: "Turkmenistan", code: "TM", provinces: ["Ahal", "Balkan", "Daşoguz", "Lebap", "Mary"], cities: ["Ashgabat", "Türkmenabat", "Daşoguz"] },
      { name: "Ukraine", code: "UA", provinces: ["Cherkasy", "Chernihiv", "Dnipropetrovsk", "Kharkiv", "Kyiv", "Lviv", "Odessa"], cities: ["Kyiv", "Kharkiv", "Odessa", "Dnipro"] },
      { name: "United Kingdom", code: "GB", provinces: ["England", "Northern Ireland", "Scotland", "Wales"], cities: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool"] },
      { name: "Uzbekistan", code: "UZ", provinces: ["Andijan", "Bukhara", "Fergana", "Namangan", "Samarqand", "Tashkent"], cities: ["Tashkent", "Namangan", "Samarqand"] }
    ]
  },
  EMRO: {
    name: "Eastern Mediterranean Region", code: "EMRO", color: "#C5383C", emoji: "🌍",
    countries: [
      { name: "Afghanistan", code: "AF", provinces: ["Badakhshan", "Balkh", "Bamyan", "Herat", "Kabul", "Kandahar"], cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"] },
      { name: "Bahrain", code: "BH", provinces: ["Capital", "Central", "Muharraq", "Northern", "Southern"], cities: ["Manama", "Riffa", "Muharraq"] },
      { name: "Egypt", code: "EG", provinces: ["Alexandria", "Aswan", "Cairo", "Giza", "Luxor", "Qalyubia"], cities: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima"] },
      { name: "Iran", code: "IR", provinces: ["Alborz", "East Azerbaijan", "Esfahan", "Fars", "Khorasan Razavi", "Tehran"], cities: ["Tehran", "Mashhad", "Isfahan", "Karaj"] },
      { name: "Iraq", code: "IQ", provinces: ["Al Anbar", "Al Basrah", "Baghdad", "Dohuk", "Erbil", "Mosul"], cities: ["Baghdad", "Basra", "Mosul", "Erbil"] },
      { name: "Jordan", code: "JO", provinces: ["Amman", "Aqaba", "Balqa", "Irbid", "Zarqa"], cities: ["Amman", "Zarqa", "Irbid"] },
      { name: "Kuwait", code: "KW", provinces: ["Al Ahmadi", "Al Asimah", "Al Farwaniyah", "Hawalli"], cities: ["Kuwait City", "Al Ahmadi", "Hawalli"] },
      { name: "Lebanon", code: "LB", provinces: ["Akkar", "Beirut", "Bekaa", "Mount Lebanon", "Tripoli"], cities: ["Beirut", "Tripoli", "Sidon"] },
      { name: "Libya", code: "LY", provinces: ["Benghazi", "Misrata", "Sabha", "Tripoli", "Zawiya"], cities: ["Tripoli", "Benghazi", "Misrata"] },
      { name: "Morocco", code: "MA", provinces: ["Casablanca-Settat", "Drâa-Tafilalet", "Fès-Meknès", "Marrakech-Safi", "Rabat-Salé-Kénitra"], cities: ["Casablanca", "Rabat", "Fes", "Marrakech"] },
      { name: "Oman", code: "OM", provinces: ["Ad Dakhiliyah", "Al Batinah", "Al Wusta", "Dhofar", "Muscat"], cities: ["Muscat", "Seeb", "Salalah"] },
      { name: "Pakistan", code: "PK", provinces: ["Balochistan", "Gilgit-Baltistan", "Khyber Pakhtunkhwa", "Punjab", "Sindh"], cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Islamabad"] },
      { name: "Qatar", code: "QA", provinces: ["Ad Dawhah", "Al Khawr", "Al Rayyan", "Al Wakrah"], cities: ["Doha", "Al Rayyan", "Umm Salal"] },
      { name: "Saudi Arabia", code: "SA", provinces: ["Asir", "Eastern Province", "Hail", "Makkah", "Riyadh"], cities: ["Riyadh", "Jeddah", "Mecca", "Medina"] },
      { name: "Somalia", code: "SO", provinces: ["Awdal", "Banaadir", "Bari", "Bay", "Mudug"], cities: ["Mogadishu", "Hargeisa", "Bosaso"] },
      { name: "Sudan", code: "SD", provinces: ["Blue Nile", "El Gezira", "Kassala", "Khartoum", "Northern"], cities: ["Khartoum", "Omdurman", "Port Sudan"] },
      { name: "Syrian Arab Republic", code: "SY", provinces: ["Al-Hasakah", "Aleppo", "Damascus", "Deir ez-Zor", "Homs", "Latakia"], cities: ["Damascus", "Aleppo", "Homs", "Latakia"] },
      { name: "Tunisia", code: "TN", provinces: ["Ariana", "Ben Arous", "Gabès", "Sfax", "Sousse", "Tunis"], cities: ["Tunis", "Sfax", "Sousse"] },
      { name: "United Arab Emirates", code: "AE", provinces: ["Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras Al Khaimah", "Sharjah"], cities: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain"] },
      { name: "Yemen", code: "YE", provinces: ["Aden", "Al Hudaydah", "Hadramaut", "Ibb", "Sanaa"], cities: ["Sanaa", "Aden", "Taiz"] }
    ]
  },
  WPRO: {
    name: "Western Pacific Region", code: "WPRO", color: "#44BBA4", emoji: "🌏",
    countries: [
      { name: "Australia", code: "AU", provinces: ["New South Wales", "Northern Territory", "Queensland", "South Australia", "Victoria", "Western Australia"], cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"] },
      { name: "Brunei Darussalam", code: "BN", provinces: ["Belait", "Brunei and Muara", "Temburong", "Tutong"], cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria"] },
      { name: "Cambodia", code: "KH", provinces: ["Banteay Meanchey", "Battambang", "Kampong Cham", "Phnom Penh", "Siem Reap"], cities: ["Phnom Penh", "Siem Reap", "Preah Sihanouk"] },
      { name: "China", code: "CN", provinces: ["Beijing", "Fujian", "Guangdong", "Jiangsu", "Shandong", "Shanghai", "Sichuan", "Zhejiang"], cities: ["Shanghai", "Beijing", "Chongqing", "Guangzhou", "Shenzhen"] },
      { name: "Cook Islands", code: "CK", provinces: ["Aitutaki", "Mangaia", "Rarotonga"], cities: ["Avarua"] },
      { name: "Fiji", code: "FJ", provinces: ["Ba", "Cakaudrove", "Kadavu", "Naitasiri", "Rewa"], cities: ["Suva", "Lautoka", "Nausori"] },
      { name: "Japan", code: "JP", provinces: ["Aichi", "Chiba", "Fukuoka", "Hokkaido", "Hyogo", "Kanagawa", "Osaka", "Tokyo"], cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo"] },
      { name: "Kiribati", code: "KI", provinces: ["Gilbert Islands", "Line Islands", "Phoenix Islands"], cities: ["South Tarawa"] },
      { name: "Lao PDR", code: "LA", provinces: ["Attapeu", "Bokeo", "Bolikhamsai", "Champasak", "Vientiane Prefecture"], cities: ["Vientiane", "Savannakhet", "Pakse"] },
      { name: "Malaysia", code: "MY", provinces: ["Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Perak", "Sabah", "Sarawak", "Selangor"], cities: ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam"] },
      { name: "Marshall Islands", code: "MH", provinces: ["Ralik Chain", "Ratak Chain"], cities: ["Majuro", "Ebeye"] },
      { name: "Micronesia", code: "FM", provinces: ["Chuuk", "Kosrae", "Pohnpei", "Yap"], cities: ["Palikir", "Weno", "Kolonia"] },
      { name: "Mongolia", code: "MN", provinces: ["Arkhangai", "Bayan-Ölgii", "Darkhan-Uul", "Khentii", "Ulaanbaatar"], cities: ["Ulaanbaatar", "Erdenet", "Darkhan"] },
      { name: "Nauru", code: "NR", provinces: ["Aiwo", "Baiti", "Denigomodu", "Nibok"], cities: ["Yaren", "Denigomodu"] },
      { name: "New Zealand", code: "NZ", provinces: ["Auckland", "Bay of Plenty", "Canterbury", "Hawke's Bay", "Wellington"], cities: ["Auckland", "Wellington", "Christchurch", "Hamilton"] },
      { name: "Niue", code: "NU", provinces: ["Niue"], cities: ["Alofi"] },
      { name: "Palau", code: "PW", provinces: ["Aimeliik", "Airai", "Koror", "Ngardmau"], cities: ["Ngerulmud", "Koror"] },
      { name: "Papua New Guinea", code: "PG", provinces: ["Central", "Chimbu", "East New Britain", "Eastern Highlands", "Morobe", "National Capital"], cities: ["Port Moresby", "Lae", "Mount Hagen"] },
      { name: "Philippines", code: "PH", provinces: ["Cebu", "Davao del Sur", "Iloilo", "Laguna", "Metro Manila", "Rizal", "Zamboanga del Sur"], cities: ["Quezon City", "Manila", "Davao", "Caloocan", "Cebu"] },
      { name: "Republic of Korea", code: "KR", provinces: ["Busan", "Daegu", "Daejeon", "Gyeonggi", "Incheon", "Seoul"], cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"] },
      { name: "Samoa", code: "WS", provinces: ["A'ana", "Aiga-i-le-Tai", "Atua", "Upolu", "Savai'i"], cities: ["Apia", "Asau", "Mulifanua"] },
      { name: "Singapore", code: "SG", provinces: ["Central Region", "East Region", "North Region", "North-East Region", "West Region"], cities: ["Singapore"] },
      { name: "Solomon Islands", code: "SB", provinces: ["Central", "Guadalcanal", "Isabel", "Malaita", "Western"], cities: ["Honiara", "Auki", "Gizo"] },
      { name: "Tonga", code: "TO", provinces: ["Ha'apai", "Tongatapu", "Vava'u"], cities: ["Nukuʻalofa", "Neiafu", "Haveluloto"] },
      { name: "Tuvalu", code: "TV", provinces: ["Funafuti", "Nanumanga", "Nanumea"], cities: ["Funafuti"] },
      { name: "Vanuatu", code: "VU", provinces: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"], cities: ["Port Vila", "Luganville", "Norsup"] },
      { name: "Viet Nam", code: "VN", provinces: ["An Giang", "Hanoi", "Ho Chi Minh City", "Khánh Hòa", "Nghệ An", "Thanh Hóa"], cities: ["Hanoi", "Ho Chi Minh City", "Haiphong", "Da Nang"] }
    ]
  }
};

// Allow this exact file to be reused by the Node backend
if (typeof module !== "undefined" && module.exports) {
  module.exports = WHO_REGIONS_CLIENT;
}
